services:
  echotune:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echotune
    restart: unless-stopped
    ports:
      - "22023:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://postgres:EchotunePg2026@echotune-postgres-aedxly:5432/echotune
